# This file was generated by GoReleaser. DO NOT EDIT.
cask "convctl" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "e5037dd78b93ac043f1bc8c5f105b6484e575d3d5c67ae8b40587a36d6fddb76"
      url "https://github.com/terasky-oss/declarative-conversion-operator/releases/download/v#{version}/declarative-conversion-operator-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13e33d1365e2509fdb23677c10b88f14b264579f3c7e79eaf1b0c7ab0bca0b8e"
      url "https://github.com/terasky-oss/declarative-conversion-operator/releases/download/v#{version}/declarative-conversion-operator-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6679f8dee1a80a6ce112f4f89447e0d47fa15ecf73df66fdfa387a8502fec026"
      url "https://github.com/terasky-oss/declarative-conversion-operator/releases/download/v#{version}/declarative-conversion-operator-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d5ddeeecbbbabb91a2350858989f7b126341e537ec628b1a003c115730cbe0f"
      url "https://github.com/terasky-oss/declarative-conversion-operator/releases/download/v#{version}/declarative-conversion-operator-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "convctl"
  desc "CLI for the declarative conversion operator"
  homepage "https://terasky-oss.github.io/declarative-conversion-operator/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "convctl"

  # No zap stanza required

end
